apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name}}-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Values.Deployment.AppName}}
  strategy:
    type: {{ .Values.Deployment.Updatetype}}
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: {{ .Values.Deployment.AppName}}
    spec:
      containers:
        - name: {{ .Values.Deployment.AppName}}
          image: {{ .Values.Deployment.Image}}
          ports:
            - containerPort: {{ .Values.Service.ContainerPort}}
