apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name}}-{{.Values.Service.Name}}
spec:
  type: NodePort
  selector:
    app: book-server
  ports:
    - port: {{.Values.Service.ServicePort}}
      targetPort: {{ .Values.Service.ContainerPort }}
      nodePort: 30000