apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - image: rokibulhasan114/book-api:v0.0.5
      name: mypod
      ports:
        - containerPort: 3333
          name: http
          protocol: TCP